version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ~/config/ngnxpm/data:/data
      - ~/config/ngnxpm/letsencrypt:/etc/letsencrypt
networks:
  default:
    external:
      name: proxy

